version: "3"
services:
  web_geldarnetwork:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3019:3000"
    volumes: 
      - ./geldarnetwork:/opt/app
      - gem_cache_geldarnetwork:/gems
    env_file: 
      - .env/development/database_geldarnetwork
      - .env/development/web_geldarnetwork
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_geldarnetwork
      - DELAYED_JOB_HOST=delayed_job_geldarnetwork
  webpack_dev_server_geldarnetwork:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3054:3054"
    volumes: 
      - ./geldarnetwork:/opt/app
      - gem_cache_geldarnetwork:/gems
    env_file: 
      - .env/development/database_geldarnetwork
      - .env/development/web_geldarnetwork
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  delayed_job_geldarnetwork:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/rails jobs:work
    volumes: 
      - ./geldarnetwork:/opt/app
      - gem_cache_geldarnetwork:/gems
    env_file: 
      - .env/development/database_geldarnetwork
      - .env/development/web_geldarnetwork
    environment: 
      - DELAYED_JOB_HOST=0.0.0.0
  database_geldarnetwork:
    image: postgis/postgis
    env_file: 
      - .env/development/database_geldarnetwork
    volumes: 
      - db_data_geldarnetwork:/var/lib/postgresql/data
volumes: 
  db_data_geldarnetwork:
  gem_cache_geldarnetwork: